import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pathfinity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Root layout no longer injects the chat sidebar globally.
            Routes that need the sidebar are placed inside the
            `(with-sidebar)` route group which provides the SidebarProvider
            and ChatSidebar. This keeps pages such as `/login` and `/signup`
            free of the sidebar. */}
        <main className="flex-1 overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}

